#!/bin/bash
#
# Font Generation Script for Weather Station Display
# 
# This script generates C header files from TrueType fonts with extended
# character support including the Latin-1 Supplement range (0xA0-0xFF)
# which contains the degree symbol (°) and other extended characters.
#
# Usage: ./generate_fonts.sh
#

set -e

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Font parameters
FONT_DIR="$PROJECT_ROOT/gui/Fonts"
FONTCONVERT="$SCRIPT_DIR/fontconvert_extended.py"

# Check if fontconvert script exists
if [ ! -f "$FONTCONVERT" ]; then
    echo "Error: fontconvert_extended.py not found at $FONTCONVERT"
    exit 1
fi

# Check if font directory exists
if [ ! -d "$FONT_DIR" ]; then
    echo "Error: Font directory not found at $FONT_DIR"
    exit 1
fi

echo "========================================="
echo "Font Generation for Weather Station"
echo "========================================="
echo ""
echo "Project root: $PROJECT_ROOT"
echo "Font directory: $FONT_DIR"
echo "Font converter: $FONTCONVERT"
echo ""

# Generate all variants
for weight in Regular Medium; do
    for size in 12 20 32; do
        font_file="$FONT_DIR/MPLUSRounded1c-${weight}.ttf"
        output_file="$FONT_DIR/mplus_rounded_1c_${weight,,}_${size}.h"
        font_name="MPLUSRounded1c_${weight}_${size}"
        
        if [ ! -f "$font_file" ]; then
            echo "Warning: Font file not found: $font_file"
            continue
        fi
        
        echo "Generating: $font_name (size $size)"
        echo "  Input:  $(basename "$font_file")"
        echo "  Output: $(basename "$output_file")"
        
        # Generate font header, skipping the first 2 lines (pragma once and include)
        # that are generated by fontconvert, then prepend our own header
        python3 "$FONTCONVERT" \
            --compress \
            "$font_name" \
            "$size" \
            "$font_file" 2>/dev/null | tail -n +3 > "$output_file.tmp"
        
        # Prepend proper header with C++ guards
        {
            echo '#pragma once'
            echo '#include "epd_driver.h"'
            echo ''
            echo '#ifdef __cplusplus'
            echo 'typedef GFXfont EpdFont;'
            echo 'typedef GFXglyph EpdGlyph;'
            echo 'typedef UnicodeInterval EpdUnicodeInterval;'
            echo '#endif'
            echo ''
            cat "$output_file.tmp"
        } > "$output_file"
        
        rm "$output_file.tmp"
        
        # Count glyphs and report size
        glyph_count=$(grep -c "^    { " "$output_file" || echo "0")
        file_size=$(wc -c < "$output_file")
        
        echo "  ✓ Generated: $file_size bytes, $glyph_count glyphs"
        echo ""
    done
done

echo "========================================="
echo "Font generation complete!"
echo ""
echo "Generated fonts include:"
echo "  - Basic ASCII (0x20-0x7E): 95 characters"
echo "  - Latin-1 Supplement (0xA0-0xFF): 96 characters"
echo "  - Total: 191 characters per font"
echo ""
echo "Special characters included:"
echo "  - Degree symbol (°) at 0xB0"
echo "  - Non-breaking space at 0xA0"
echo "  - Extended Latin characters (à, é, ñ, etc.)"
echo "========================================="
